FPTBook/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FPTBook.DB;
using FPTBook.Models;

namespace FPTBook.Controllers
{
    public class BooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Books
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.Category);
            return View(books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.categoryID = new SelectList(db.Categories, "categoryID", "categoryName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "bookID,bookName,description,Img,stock_quantity,price,categoryID")] Book book, HttpPostedFileBase file)
        {
           string pic = System.IO.Path.GetFileName(file.FileName);
           string checkImg = Path.GetExtension(file.FileName);
            if (checkImg.ToLower() == ".jpg" || checkImg.ToLower() == ".jpeg" || checkImg.ToLower() == ".png" && file != null && file.ContentLength > 0)
            {
                string path = Path.Combine(Server.MapPath("~/assets/img"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                book.Img = pic.ToString();
                if (ModelState.IsValid)
                {
                    db.Books.Add(book);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewBag.CheckError = "Invavlid file";
            }

            ViewBag.categoryID = new SelectList(db.Categories, "categoryID", "categoryName", book.categoryID);
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.categoryID = new SelectList(db.Categories, "categoryID", "categoryName", book.categoryID);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book, HttpPostedFileBase file, int id)
        {
            if (ModelState.IsValid)
            {
                Book book1 = db.Books.Find(id);
                if (file != null && file.ContentLength > 0)
                {
                    string pic= "";
                    string file_name = book.Img;
                    string path1 = Server.MapPath("~/assets/img/");
                    string checkimg = Path.GetExtension(file.FileName);
                    if (checkimg.ToLower() == ".jpg" || checkimg.ToLower() == ".jpeg" || checkimg.ToLower() == ".png")
                    {
                        FileInfo file1 = new FileInfo(path1 + file_name);
                        if (file1.Exists)
                        {
                            file1.Delete();
                        }
                        pic = System.IO.Path.GetFileName(file.FileName);
                        string path = Path.Combine(Server.MapPath("~/assets/img/"), Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        book1.Img = pic.ToString();
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.CheckError = "*Invavlid file";
                    }
                }
                else
                {
                    book1.bookName = book.bookName;
                    book1.stock_quantity = book.stock_quantity;
                    book1.price = book.price;
                    book1.description = book.description;
                    book1.categoryID = book.categoryID;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            ViewBag.categoryID = new SelectList(db.Categories, "categoryID", "categoryName", book.categoryID);
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FPTBook/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FPTBook.DB;
using FPTBook.Models;

namespace FPTBook.Controllers
{
    public class CategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "categoryID,categoryName,description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "categoryID,categoryName,description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FPTBook/Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FPTBook.DB;
using FPTBook.Models;

namespace FPTBook.Controllers
{
    public class ManageUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ManageUsers
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: ManageUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
       

        // GET: ManageUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: ManageUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "username,password,confirmPassword,fullname,telephone,email,address,gender,birthday,state")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: ManageUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: ManageUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FPTBook/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FPTBook.DB;
using FPTBook.Models;

namespace FPTBook.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.User);
            return View(orders.ToList());
        }


        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FPTBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bentham|Playfair+Display|Raleway:400,500|Suranna|Trocchi" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=ABeeZee&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aclonica&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
    <link rel="stylesheet" href="~/assets/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="~/assets/fonts/simple-line-icons.min.css">
    <link rel="stylesheet" href="~/assets/fonts/fontawesome5-overrides.min.css">
    <link rel="stylesheet" href="~/assets/css/Black-Navbar.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="~/assets/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="~/assets/css/Ludens-Users---25-After-Register.css">
    <link rel="stylesheet" href="~/assets/css/Pretty-Registration-Form.css">
    <link rel="stylesheet" href="~/assets/css/Register-form.css">
    <link rel="stylesheet" href="~/assets/css/Aboutus.css">
    <link rel="stylesheet" href="~/assets/css/Contact.css">
    <link rel="stylesheet" href="~/assets/css/Product.css">
    <link rel="stylesheet" href="~/assets/css/icon.css">
    <link rel="stylesheet" href="~/assets/css/Product - Detail.css">
    <link rel="stylesheet" href="~/assets/css/Registration-Form-with-Photo.css">
    <link rel="stylesheet" href="~/assets/css/untitled.css">
    <link rel="stylesheet" href="~/assets/css/vanilla-zoom.min.css">

</head>
<body>
    <header>
        <!-- Start: Black-Navbar -->
        <nav class="navbar navbar-light navbar-expand-md navbar-fixed-top navigation-clean-button" style="background: var(--bs-dark);border-style: none;padding-top: 0;padding-bottom: 10px;margin-top: 0px;min-height: 8px;color: var(--bs-yellow);">
            <div class="container">
                <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1" style="color: var(--bs-yellow);"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon" style="color: var(--bs-yellow);"></span></button>
                <div><a class="navbar-brand" href="@Url.Action("Index", "Home")"><span style="color: var(--bs-yellow);font-family: ABeeZee, sans-serif;font-size: 32px;">FPTBook Store </span> </a></div>
                <div class="collapse navbar-collapse" id="navcol-1" style="color: var(--bs-dark);">
                    <ul class="navbar-nav nav-right">
                        <li class="nav-item"><a class="nav-link active" style="color: var(--bs-yellow)" @Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="nav-item"><a class="nav-link active"  style="color: var(--bs-yellow);" @Html.ActionLink("About us", "About", "Home")</a></li>
                        <li class="nav-item"><a class="nav-link"  style="color: var(--bs-yellow);"@Html.ActionLink("Contact","Contact", "Home")</a></li>

                    </ul>
                    @using (Html.BeginForm())
                    {
                        <div class="row">
                            <div class="col col-sm-9">
                                @Html.TextBox("searchstring", "", new { @class = "form-control", @type = "text", @placeholder = " Search", @style = "width: 200px;" })
                            </div>
                            <div class="col col-sm-3">
                                <i type="submit" class="fa fa-search" style="font-size: 29px; color:  var(--bs-yellow)"></i>
                            </div>
                        </div>
                    }
                    @if (Session["username"] != null)
                    {
                        <a href="@Url.Action("ViewCart","Cart")">
                            <i class="fa fa-shopping-cart" style="background: var(--bs-gray-900);border-color: var(--bs-yellow);color: var(--bs-yellow);">@Html.Action("BagCart", "Cart")</i>
                        </a>
                        <p class="ms-auto navbar-text actions" style="text-align: right;">
                            <a class="login" style="color: rgba(224,217,217,0.9);" @Html.ActionLink($"Hello!{Session["username"]}", "EditInfor", "Users")
                            <a class="btn btn-primary" style="color: rgba(0,0,0,0.9);background: var(--bs-gray-200);border-radius: 10px;border-style: solid;
                        border-color: rgba(0,0,0,0.9);font-size: 16px;padding: 5px 8px;" @Html.ActionLink("Logout","Logout","Users")
                        </p>
                    }
                    else
                    {
                        <p class="ms-auto navbar-text actions" style="text-align: right;">
                            <a class="login" style="color: rgba(224,217,217,0.9);" @Html.ActionLink("Sign in", "Login", "Users")
                            <a class="btn btn-light action-button" role="button" style="color: rgba(0,0,0,0.9);background: var(--bs-gray-200);border-radius: 10px;border-style: solid;
                        border-color: rgba(0,0,0,0.9);font-size: 16px;padding: 5px 8px;"@Html.ActionLink("Sign up","Register","Users")
                        </p><!-- End: Actions -->
                    }

                </div>
                    </div>

        </nav><!-- End: Black-Navbar -->
    </header><!-- Start: Footer Dark -->
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer class="page-footer dark" style="background-color:black">
            <div class="container">
                <div class="row">

                    <div class="col-sm-3">
                        <h5 style="color: var(--bs-white);">FPTBook</h5>
                        <ul>
                            <li class="nav-item"><a class="nav-link" href="#" style="color: var(--bs-yellow);">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="#" style="color: var(--bs-yellow);">About us</a></li>
                            <li class="nav-item"><a class="nav-link" href="#" style="color: var(--bs-yellow);">Contact us<br><br></a></li>
                        </ul>
                    </div>
                    <div class="col-sm-3">
                        <h5 style="color: var(--bs-white);">Acount</h5>
                        <ul>
                            @if (Session["username"] != null)
                            {
                                <li class="nav-item"><a class="nav-link" href="#" style="color: var(--bs-yellow);" @Html.ActionLink("Account", "EditInfor", "Users")</li>
                            }
                            else
                            {
                                <li class="nav-item"><a class="nav-link" style="color: var(--bs-yellow);" @Html.ActionLink("Sign in", "Login", "Users")</li>
                                <li class="nav-item"><a class="nav-link" style="color: var(--bs-yellow);" @Html.ActionLink("Sign up", "Register", "Users")</li>
                            }


                        </ul>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons" style="background-color:black"><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-youtube"></i></a></div>
                    </div>

                    </div>
                </div>
        </footer><!-- End: Footer Dark -->
    </div>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="~/assets/js/vanilla-zoom.js"></script>
    <script src="~/assets/js/theme.js"></script>
    <script src="~/assets/js/dt.js"></script>
    <script src="https://geodata.solutions/includes/countrystate.js"></script><!-- End: Footer Dark -->
</body>
</html>

FPTBook/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/assetsadmin/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assetsadmin/css/Features-Boxed.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="~/assetsadmin/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/assetsadmin/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/assetsadmin/fonts/fontawesome5-overrides.min.css">
</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0" style="background: var(--bs-yellow);">
            <div class="container-fluid d-flex flex-column p-0">
                <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="@Url.Action("Index","Admin")">
                    <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-laugh-wink"></i></div>
                    <div class="sidebar-brand-text mx-3"><span href=@Url.Action("Index","Admin")>FPTBook</span></div>
                </a>
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    <li class="nav-item"><a class="nav-link active"  href=@Url.Action("Index","Admin")><i class="fas fa-tachometer-alt"></i><span>Management&nbsp;</span></a></li>
                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Index","Categories")>
                            <i class="fa fa-caret-square-o-right" style="color: var(--bs-gray-900);"></i>
                            <span style="color: var(--bs-gray-900);">Manage Category</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Index","Books")>
                            <i class="fa fa-book" style="color: var(--bs-gray-900);"></i>
                            <span style="color: var(--bs-gray-900);">Manage Book</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Index","Orders")>
                            <i class="fa fa-shopping-cart" style="color: var(--bs-gray-900);"></i>
                            <span style="color: var(--bs-gray-900);">Manage Orders</span>
                        </a>
                    </li>
                    <li class="nav-item"></li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index","ManageUsers")"><i class="fa fa-user" style="color: var(--bs-gray-900);"></i><span style="color: var(--bs-gray-900);">Manage User</span></a></li>
                    <li class="nav-item"><a class="nav-link"href="@Url.Action("EditInfor","Admin")"><i class="far fa-user-circle" style="color: var(--bs-gray-900);"></i><span style="color: var(--bs-gray-900);">Account</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Logout","Users")"><i class="fas fa-user-circle" style="color: var(--bs-gray-900);"></i><span style="color: var(--bs-gray-900);">Logout</span></a></li>
                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button" style="color: var(--bs-danger);"></button></div>
            </div>
        </nav>
        <div class="container body-content">
            @RenderBody()
        </div>
    </div>
        <script src="~/assetsadmin/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/assetsadmin/js/theme.js"></script>
</body>
</html>